---
title: "U-BDS training guides"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About

The UAB Biological Data Science Core (U-BDS) is a research resource that provides services to the UAB community in a variety of tasks linked to analysis, training, pipeline and app development. For more information linked to the core and its services please visit the main U-BDS page at: <https://www.uab.edu/cores/ircp/bds>

__This page is specifically dedicated to training resources we share__. Our long-term goal is to continue to add more training guides which will aid the scientific community in the implementation of commonly used resources in computational biology. Thus, please check back regularly for new material. If you have any ideas for training guides, please open an issue linked to the GitHub of this webpage describing the topic you would like to see: <https://github.com/U-BDS/training_guides/issues> ; __NOTE__ that we will prioritize topics which overlap with areas of research/support we offer at U-BDS.

## Research Team

* Director: Liz Worthey, Ph.D.
* Co-Director: Brittany Lasseigne, Ph.D.
* Managing Director: Lara Ianov, Ph.D.
* U-BDS staff:
  * Austyn Trull, B.Sc.
  * Bharat Mishra, Ph.D.
  
This resource is actively maintained by Lara Ianov and the U-BDS staff.

# Training

U-BDS offers weekly data science office hours on Thursdays from 1:30pm-2:00pm. If you are a UAB trainee, staff or faculty please feel free to stop by. The Zoom information is in the `#datascience` channel of the following Slack group: <https://join.slack.com/t/uablabs/signup> (if you can find, just ask in `#datascience`)

# Other resources

In collaboration with Dr. Lasseigne and her lab, be sure sure to check the training guides hosted at her lab's website. Please visit the following for more information: <https://www.lasseigne.org/education/>

# Twitter

Follow us at <https://twitter.com/UAB_BDS> - `@UAB_BDS`
